---
- name: Check Data Center Facts
  hosts: workstation.lab.example.com
  vars:
    fact_dir: /home/student/ansible/grading/output

  tasks:
    - name: Create fact directory
      file:
        path: "{{ fact_dir }}"
        state: directory
        owner: student
        group: student
        mode: 0775

    - name: Check Default data center Facts
      ovirt_datacenter_facts:
        auth: "{{ rhvm_auth }}"
        pattern: name="Default"
        fetch_nested: true

    - name: Template Default data center Facts
      vars:
        nice_facts: "{{ ovirt_datacenters[0] | to_nice_yaml }}"
      template:
        src: templates/dc.yml.j2
        dest: "{{ fact_dir }}/dc-Default.yml"
      when: ovirt_datacenters[0] is defined

    - name: Check {{ dc_ge[0]['name'] }} data center Facts
      ovirt_datacenter_facts:
        auth: "{{ rhvm_auth }}"
        pattern: name="{{ dc_ge[0]['name'] }}"
        fetch_nested: true

    - name: Template {{ dc_ge[0]['name'] }} data center Facts
      vars:
        nice_facts: "{{ ovirt_datacenters[0] | to_nice_yaml }}"
      template:
        src: templates/dc.yml.j2
        dest: "{{ fact_dir }}/dc-{{ dc_ge[0]['name'] }}.yml"
      when: ovirt_datacenters[0] is defined

    - name: Check {{ dc_lab[0]['name'] }} data center Facts
      ovirt_datacenter_facts:
        auth: "{{ rhvm_auth }}"
        pattern: name="{{ dc_lab[0]['name'] }}"
        fetch_nested: true

    - name: Template {{ dc_lab[0]['name'] }} data center Facts
      vars:
        nice_facts: "{{ ovirt_datacenters[0] | to_nice_yaml }}"
      template:
        src: templates/dc.yml.j2
        dest: "{{ fact_dir }}/dc-{{ dc_lab[0]['name'] }}.yml"
      when: ovirt_datacenters[0] is defined

