---
- name: Check Network Facts
  hosts: workstation.lab.example.com
  vars:
    fact_dir: /home/student/ansible/grading/output

  tasks:
    - name: Create fact directory
      file:
        path: "{{ fact_dir }}"
        state: directory
        owner: student
        group: student
        mode: 0775

    - name: Check logical network facts in the {{ dc_default[0]['name'] }} data center
      ovirt_network_facts:
        auth: "{{ rhvm_auth }}"
        pattern: datacenter="{{ dc_default[0]['name'] }}"
        fetch_nested: true

    - name: Template logical networks from the {{ dc_default[0]['name'] }} data center
      vars:
        nice_facts: "{{ item | to_nice_yaml }}"
      template:
        src: templates/network.yml.j2
        dest: "{{ fact_dir }}/network-{{ dc_default[0]['name'] }}-{{ item['name'] }}.yml"
      loop: "{{ ovirt_networks }}"
      loop_control:
        label: Writing facts for {{ item['name'] }} in the {{ dc_default[0]['name'] }} data center
      when: ovirt_networks[0] is defined

    - name: Check logical network facts in the {{ dc_ge[0]['name'] }} data center
      ovirt_network_facts:
        auth: "{{ rhvm_auth }}"
        pattern: datacenter="{{ dc_ge[0]['name'] }}"
        fetch_nested: true

    - name: Template logical networks from the {{ dc_ge[0]['name'] }} data center
      vars:
        nice_facts: "{{ item | to_nice_yaml }}"
      template:
        src: templates/network.yml.j2
        dest: "{{ fact_dir }}/network-{{ dc_ge[0]['name'] }}-{{ item['name'] }}.yml"
      loop: "{{ ovirt_networks }}"
      loop_control:
        label: Writing facts for {{ item['name'] }} in the {{ dc_ge[0]['name'] }} data center
      when: ovirt_networks[0] is defined

    - name: Check logical network facts in the {{ dc_lab[0]['name'] }} data center
      ovirt_network_facts:
        auth: "{{ rhvm_auth }}"
        pattern: datacenter="{{ dc_lab[0]['name'] }}"
        fetch_nested: true

    - name: Template logical networks from the {{ dc_lab[0]['name'] }} data center
      vars:
        nice_facts: "{{ item | to_nice_yaml }}"
      template:
        src: templates/network.yml.j2
        dest: "{{ fact_dir }}/network-{{ dc_lab[0]['name'] }}-{{ item['name'] }}.yml"
      loop: "{{ ovirt_networks }}"
      loop_control:
        label: Writing facts for {{ item['name'] }} in the {{ dc_lab[0]['name'] }} data center
      when: ovirt_networks[0] is defined

