---
- name: Remove Fact Directory
  hosts: workstation.lab.example.com
  vars:
    fact_dir: /home/student/ansible/grading/output

  tasks:
    - name: Remove fact directory
      file:
        path: "{{ fact_dir }}"
        state: absent
