---
- name: Check User Facts
  hosts: workstation.lab.example.com
  vars:
    fact_dir: /home/student/ansible/grading/comp-review/output

  tasks:
    - name: Create fact directory
      file:
        path: "{{ fact_dir }}"
        state: directory
        owner: student
        group: student
        mode: 0775

    - name: Gather LDAP user facts
      ovirt_user_facts:
        auth: "{{ rhvm_auth }}"
        pattern: lab.example.com-authz
        fetch_nested: true

    - name: Write out user facts
      vars:
        nice_facts: "{{ item | to_nice_yaml }}"
      template:
        src: generic.yml.j2
        dest: "{{ fact_dir }}/user-{{ item['principal'] }}.yml"
      when: ovirt_users[0] is defined
      loop: "{{ ovirt_users }}"
      loop_control:
        label: Writing out facts for user {{ item['principal'] }}.
