---
- name: Check Host Facts
  hosts: workstation.lab.example.com
  vars:
    fact_dir: /home/student/ansible/grading/comp-review/output

  tasks:
    - name: Create fact directory
      file:
        path: "{{ fact_dir }}"
        state: directory
        owner: student
        group: student
        mode: 0775

    - name: Gather host facts
      ovirt_host_facts:
        auth: "{{ rhvm_auth }}"
        fetch_nested: true

    - name: Write out host facts
      vars:
        nice_facts: "{{ item | to_nice_yaml }}"
      template:
        src: generic.yml.j2
        dest: "{{ fact_dir }}/{{ item['name'] }}.yml"
      when: ovirt_hosts[0] is defined
      loop: "{{ ovirt_hosts }}"
      loop_control:
        label: Writing out facts for host {{ item['name'] }}.
