---
- name: Check VM Facts
  hosts: workstation.lab.example.com
  vars:
    fact_dir: /home/student/ansible/grading/comp-review/output

  tasks:
    - name: Create fact directory
      file:
        path: "{{ fact_dir }}"
        state: directory
        owner: student
        group: student
        mode: 0775

    - name: Gather virtual machine facts
      ovirt_vm_facts:
        auth: "{{ rhvm_auth }}"
        fetch_nested: true

    - name: Write out virtual machine facts
      vars:
        nice_facts: "{{ item | to_nice_yaml }}"
      template:
        src: generic.yml.j2
        dest: "{{ fact_dir }}/vm-{{ item['name'] }}-{{ item['cluster']['id'] }}.yml"
      when: ovirt_vms[0] is defined
      loop: "{{ ovirt_vms }}"
      loop_control:
        label: Writing out facts for VM {{ item['name'] }}.
