---
- name: Check Data Center Facts
  hosts: workstation.lab.example.com
  vars:
    fact_dir: /home/student/ansible/grading/comp-review/output

  tasks:
    - name: Create fact directory
      file:
        path: "{{ fact_dir }}"
        state: directory
        owner: student
        group: student
        mode: 0775

    - name: Gather data center facts
      ovirt_datacenter_facts:
        auth: "{{ rhvm_auth }}"
        fetch_nested: true

    - name: Write out data center facts
      vars:
        nice_facts: "{{ item | to_nice_yaml }}"
      template:
        src: generic.yml.j2
        dest: "{{ fact_dir }}/dc-{{ item['name'] }}.yml"
      when: ovirt_datacenters[0] is defined
      loop: "{{ ovirt_datacenters }}"
      loop_control:
        label: Writing out facts for data center {{ item['name'] }}.
