---
- name: Grade VM Disk playbook
  hosts: workstation.lab.example.com
  become: false
  vars:
    fact_dir: /home/student/ansible/grading/comp-review/output

  tasks:
    - name: Fail if vm variable is not defined
      fail:
        msg: The vm variable needs to be passed to this playbook.
      when: vm is not defined
      tags: always

    - name: Find cluster ID
      shell: "grep '^id:' {{ fact_dir }}/cluster-{{ vm[0]['cluster'] }}.yml | awk '{ print $2 }'"
      changed_when: false
      register: cluster_id
      tags: always
     
    - name: Check if variable file exists
      stat:
        path: "{{ fact_dir }}/vm-{{ vm[0]['vm_name'] }}-{{ cluster_id.stdout }}.yml"
      register: var_file
      tags: always

    - name: Fail if variable file doesn't exist
      fail:
        msg: "FAIL: {{ vm[0]['vm_name'] }} doesn't exist or doesn't exist in the {{ cluster['name'] }} cluster."
      when: var_file.stat.exists == False
      tags: always

    - name: Include variables for student work
      include_vars: "{{ fact_dir }}/vm-{{ vm[0]['vm_name'] }}-{{ cluster_id.stdout }}.yml"
      tags: always

    - block:
        - name: Check if VM disk variable file exists
          stat:
            path: "{{ fact_dir }}/disk-{{ ovirt_disks[0]['name'] }}-{{ vm[0]['vm_name'] }}-{{ vm[0]['cluster'] }}.yml"
          register: disk_var_file

        - name: The VM disk variable file needs to be created
          fail:
            msg: "FAIL: the VM disk variable file needs to be created for {{ vm[0]['vm_name'] }}"
          when: disk_var_file.stat.exists == False

      rescue:
        - name: Check Disks for VM {{ vm[0]['vm_name'] }}
          ovirt_disk_facts:
            auth: "{{ rhvm_auth }}"
            pattern: id={{ disk_attachments[0]['id'] }}
            fetch_nested: true

        - name: Template Disks for VM {{ vm[0]['vm_name'] }}
          vars:
            nice_facts: "{{ ovirt_disks[0] | to_nice_yaml }}"
          template:
            src: generic.yml.j2
            dest: "{{ fact_dir }}/disk-{{ ovirt_disks[0]['name'] }}-{{ vm[0]['vm_name'] }}-{{ vm[0]['cluster'] }}.yml"
          when: ovirt_disks[0] is defined
      tags: always

    # Check disk information: size, storage-domain, pre-allocated or thin
    - name: Include variables for student work
      include_vars: "{{ fact_dir }}/disk-{{ ovirt_disks[0]['name'] }}-{{ vm[0]['vm_name'] }}-{{ vm[0]['cluster'] }}.yml"
      tags: always

    - name: Compare disk alias
      assert:
        that: "vm[0]['vm_disks'][0]['name'] == alias"
        fail_msg: "FAIL: Expecting {{ vm[0]['vm_disks'][0]['name'] }} and got {{ alias }}"
        success_msg: "PASS: Expecting {{ vm[0]['vm_disks'][0]['name'] }} and got {{ alias }}"
      tags: check_alias

