---
- name: Assign role playbook
  hosts: workstation.lab.example.com

  tasks:
    - name: Fail if managed_users variable is not defined
      fail:
        msg: The managed_users variable needs to be passed to this playbook.
      when: managed_users is not defined

    - name: Ensuring users exist
      ovirt_user:
        auth: "{{ rhvm_auth }}"
        name: "{{ item['user_name'] }}"
        state: present
        authz_name: lab.example.com-authz
      loop: "{{ managed_users }}"
      loop_control:
        label: "Ensuring {{ item['user_name'] }} ovirt user exists."

    - name: Assigning roles
      ovirt_permission:
        auth: "{{ rhvm_auth }}"
        user_name: "{{ item.user_name }}"
        authz_name: lab.example.com-authz
        object_type: "{{ item.object_type }}"
        role: "{{ item.role }}"
        state: present
      loop: "{{ managed_users }}"
      loop_control:
        label: "User {{ item.user_name }} assigned {{ item.role }} on {{ item.object_type }}."
