---
- name: Remove OVA File
  hosts: hostc.lab.example.com
  vars:
    ova_dir: /var/lib/libvirt/images
    ova_file: rhel-lab-vm.ova

  tasks:
    - name: Fail if ova_file variable is not defined
      fail:
        msg: The ova_file variable needs to be passed to this playbook.
      when: ova_file is not defined

    - name: Remove OVA File
      file:
        path: "{{ ova_dir }}/{{ ova_file }}"
        state: absent
