---
# Removes users from IdM
# Saumik Paul <saumik@redhat.com>

- name: Create IdM users and groups
  hosts: utility.lab.example.com

  tasks:
    - name: Fail if idm_users variable is not defined
      fail:
        msg: The idm_users variable needs to be passed to this playbook.
      when: idm_users is not defined

    - name: Removing IdM users and groups
      ipa_user: 
        name: "{{ item.username }}"
        state: absent
        ipa_host: "{{ ipa_server.name }}"
        ipa_user: "{{ ipa_admin.name }}"
        ipa_pass: "{{ ipa_admin.password }}"
      loop: "{{ idm_users }}"
      loop_control:
        label: "Ensuring {{ item.username }} IdM user exists."
